version: "3"

services:
  pg:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    networks:
      - app_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
  # web:
  #   container_name: web
  #   build:
  #     context: .
  #     dockerfile: ./apps/web/Dockerfile
  #   restart: always
  #   ports:
  #     - 3000:3000
  #   networks:
  #     - app_network

  # napi:
    # container_name: napi
    # build:
    #   context: .
    #   dockerfile: ./apps/napi/Dockerfile
    # restart: always
    # ports:
    #   - 3002:3002
    # networks:
    #   - app_network
networks:
  app_network:

volumes:
  postgres_data: