/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Options {
  url: string
  params?: Record<string, string>
  headers?: Record<string, string>
  method?: string
}
export function htmlToText(html: string): string
export function processWeb(options: Options, schema: string): Promise<string>
